[package]
name = "soldiers"
version = "0.1.0"
edition = "2021"

[dependencies]
either = "1.15.0"
itertools = "0.14.0"
rust-hdl = {path = "patches/rust-hdl/rust-hdl", package = "rust-hdl"}
structstruck = "0.5.0"
vcd = "0.6.1"
